# Fixed-Duration Data from Horsager et al. 2009

In [1]:
from os import environ
import pandas as pd
import numpy as np

In [2]:
def open_excel(filename, idx_sheet=0):
    xl = pd.ExcelFile(filename)
    df = xl.parse(xl.sheet_names[idx_sheet])
    assert 'Subject' in df.columns
    assert 'Electrode' in df.columns
    assert 'pdur' in df.columns
    assert 'type' in df.columns
    assert 'data' in df.columns
    df.drop(df.index, inplace=True)
    return df

In [3]:
def load_row(df, subject, electrode, pdur, dtype='truth'):
    rows = (df['Subject'] == subject) & (df['Electrode'] == electrode) & \
           (df['type'] == dtype) & (df['pdur'] == pdur)
    if not np.any(rows):
        return None, None
    elif np.count_nonzero(rows) > 1:
        print('More than one row found:')
        print(df.loc[rows, :])
        return None, None

    # Data points: [all pdurs, all amps]
    data = np.array(df.loc[rows, 'data':])
    data = data.reshape((2, -1))
    return data[0, :], data[1, :]

In [4]:
def append_row(df, subject, electrode, theta, pdur, dtype, freqs, amps):
    # Add all data into a single np.array
    arr = np.concatenate((np.array([subject, electrode, theta, pdur, dtype]), freqs, amps))
    
    # Make a PD series from it
    newrow = pd.Series(arr, index=df.columns)
    return df.append(newrow, ignore_index=True)

In [5]:
df = open_excel(environ['SECOND_SIGHT_DATA'] + '/horsager2009/fixed-duration.xlsx')
df

Empty DataFrame
Columns: [Subject, Electrode, theta, pdur, type, data, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12, Unnamed: 13, Unnamed: 14, Unnamed: 15]
Index: []

## Fig. 4

In [6]:
truth = np.array([4.86110, 141.47024, 14.65022, 126.46864,
                  43.77047, 99.93162, 74.38898, 82.05364,
                  133.87953, 76.46330, 224.19096, 67.05204]).reshape((-1, 2))
df = append_row(df, 'S05', 'C3', 36.3, 0.075, 'truth', truth[:, 0], truth[:, 1])

pred = np.array([4.98067, 141.84635, 14.64679, 127.23795,
                 44.29250, 101.08131, 74.27555, 87.05417,
                 133.84811, 77.23261, 221.21082, 70.90287]).reshape((-1, 2))
df = append_row(df, 'S05', 'C3', 36.3, 0.075, 'pred', pred[:, 0], pred[:, 1])

truth = np.array([4.70684, 78.94737, 14.21718, 73.42105,
                  44.52019, 58.68421, 73.20578, 55.78947,
                  139.45736, 53.68421, 229.38809, 50.52632]).reshape((-1, 2))
df = append_row(df, 'S06', 'A1', 6.1, 0.075, 'truth', truth[:, 0], truth[:, 1])

pred = np.array([4.92104, 82.89474, 14.20334, 74.21053,
                 44.50573, 58.94737, 73.42011, 53.42105,
                 137.21058, 46.84211, 222.77886, 44.21053]).reshape((-1, 2))
df = append_row(df, 'S06', 'A1', 6.1, 0.075, 'pred', pred[:, 0], pred[:, 1])


truth = np.array([5.00000, 24.85981, 14.81801, 22.61682,
                  43.91469, 22.99065, 73.32742, 24.85981,
                  131.74407, 24.01869, 214.67673, 19.62617]).reshape((-1, 2))
df = append_row(df, 'S05', 'C3', 307.5, 0.975, 'truth', truth[:, 0], truth[:, 1])

pred = np.array([5.25019, 28.50467, 15.37071, 25.88785,
                 45.00000, 20.93458, 71.55891, 19.25234,
                 131.74407, 18.69159, 214.67673, 18.87850]).reshape((-1, 2))
df = append_row(df, 'S05', 'C3', 307.5, 0.975, 'pred', pred[:, 0], pred[:, 1])

truth = np.array([5.00000, 20.51724, 15.00000, 16.83908,
                  46.11213, 15.17241, 76.99664, 14.65517,
                  140.03539, 13.39080, 228.18742, 12.18391]).reshape((-1, 2))
df = append_row(df, 'S06', 'A1', 94.5, 0.975, 'truth', truth[:, 0], truth[:, 1])

pred = np.array([5.06141, 20.51724, 15.00000, 18.56322,
                 46.11213, 15.22989, 76.99664, 13.96552,
                 140.03539, 13.04598, 225.41891, 12.93103]).reshape((-1, 2))
df = append_row(df, 'S06', 'A1', 94.5, 0.975, 'pred', pred[:, 0], pred[:, 1])

## Fig. S2.3

In [7]:
truth = np.array([5.00000, 112.83784, 15.14525, 92.56757,
                  45.00000, 70.27027, 74.99495, 76.35135,
                  135.00000, 61.48649, 224.98486, 61.48649]).reshape((-1, 2))
df = append_row(df, 'S05', 'B3', 21.1, 0.075, 'truth', truth[:, 0], truth[:, 1])

truth = np.array([4.75490, 214.59597, 14.72461, 191.10352,
                  45.31173, 131.81568, 76.40481, 105.30261,
                  137.79166, 93.52883, 234.09605, 90.46412]).reshape((-1, 2))
df = append_row(df, 'S05', 'C2', 10.5, 0.075, 'truth', truth[:, 0], truth[:, 1])

truth = np.array([5.04958, 202.38095, 15.11228, 177.38095,
                  45.25887, 159.52381, 76.02583, 141.66667,
                  135.40329, 130.95238, 225.42409, 120.23810]).reshape((-1, 2))
df = append_row(df, 'S06', 'B1', 2500.0, 0.075, 'truth', truth[:, 0], truth[:, 1])

truth = np.array([5.26202, 269.35835, 15.73428, 252.16150,
                  45.90965, 156.76998, 76.21561, 159.77433,
                  135.84947, 134.85590, 225.12285, 128.48015]).reshape((-1, 2))
df = append_row(df, 'S06', 'C2', 230.0, 0.075, 'truth', truth[:, 0], truth[:, 1])

## Fig. S2.4

In [8]:
truth = np.array([5.05160, 29.55563, 15.00000, 23.71010,
                  44.54033, 23.90231, 74.42302, 22.40522,
                  132.25607, 19.37753, 218.73103, 19.01605]).reshape((-1, 2))
df = append_row(df, 'S05', 'B3', 147.0, 0.975, 'truth', truth[:, 0], truth[:, 1])

truth = np.array([4.94796, 24.84375, 15.00000, 23.12500,
                  45.95159, 22.50000, 76.72857, 20.93750,
                  139.30471, 20.93750, 232.60679, 20.31250]).reshape((-1, 2))
df = append_row(df, 'S05', 'C2', 54.0, 0.975, 'truth', truth[:, 0], truth[:, 1])

truth = np.array([5.00000, 23.00000, 14.84678, 25.16667,
                  44.08536, 25.16667, 72.91034, 22.50000,
                  132.25607, 25.83333, 218.73103, 22.83333]).reshape((-1, 2))
df = append_row(df, 'S06', 'B1', 2900.0, 0.975, 'truth', truth[:, 0], truth[:, 1])

truth = np.array([4.77221, 34.34783, 14.62270, 34.13043,
                  44.51137, 30.21739, 74.30683, 30.43478,
                  135.43058, 26.73913, 226.54974, 25.00000]).reshape((-1, 2))
df = append_row(df, 'S06', 'C2', 900.0, 0.975, 'truth', truth[:, 0], truth[:, 1])

## Fig. S3.3

In [9]:
truth = np.array([4.83173, 106.56324, 14.27496, 91.78543,
                  42.65204, 69.01394, 70.97810, 59.45306,
                  125.93917, 56.69734, 209.36605, 51.44360]).reshape((-1, 2))
df = append_row(df, 'S05', 'A1', 10.5, 0.075, 'truth', truth[:, 0], truth[:, 1])

truth = np.array([5.03690, 179.04947, 15.18142, 127.50746,
                  45.88949, 105.86506, 78.59943, 89.87519,
                  140.05534, 84.23171, 233.28153, 78.52492]).reshape((-1, 2))
df = append_row(df, 'S05', 'C4', 49.5, 0.075, 'truth', truth[:, 0], truth[:, 1])

truth = np.array([4.88165, 251.47059, 14.70626, 207.35294,
                  44.32818, 157.35294, 73.40122, 132.35294,
                  131.93299, 141.17647, 218.34075, 122.05882]).reshape((-1, 2))
df = append_row(df, 'S06', 'B2', 216.0, 0.075, 'truth', truth[:, 0], truth[:, 1])

truth = np.array([4.81146, 405.88235, 14.80072, 281.17647,
                  43.60594, 260.00000, 71.79073, 222.35294,
                  128.81898, 182.35294, 216.41555, 121.17647]).reshape((-1, 2))
df = append_row(df, 'S06', 'D1', 188.0, 0.075, 'truth', truth[:, 0], truth[:, 1])

## Fig. S3.4

In [10]:
truth = np.array([5.02108, 24.36620, 15.16171, 21.12676,
                  46.26343, 18.73239, 77.70989, 16.90141,
                  139.67851, 15.35211, 232.56079, 14.36620]).reshape((-1, 2))
df = append_row(df, 'S05', 'A1', 154.0, 0.975, 'truth', truth[:, 0], truth[:, 1])

truth = np.array([5.04799, 18.29657, 15.00000, 15.35011,
                  45.00000, 18.08696, 75.37929, 17.61648,
                  133.71647, 16.29840, 226.13788, 15.51121]).reshape((-1, 2))
df = append_row(df, 'S05', 'C4', 141.8, 0.975, 'truth', truth[:, 0], truth[:, 1])

truth = np.array([5.00000, 30.54545, 15.14525, 28.18182,
                  45.87574, 28.54545, 77.94229, 28.72727,
                  140.30555, 26.54545, 236.09113, 24.18182]).reshape((-1, 2))
df = append_row(df, 'S06', 'B2', 546.0, 0.975, 'truth', truth[:, 0], truth[:, 1])

truth = np.array([5.04799, 30.89286, 15.00000, 29.28571,
                  44.57216, 29.64286, 75.37929, 30.53571,
                  133.71647, 27.50000, 223.98784, 23.57143]).reshape((-1, 2))
df = append_row(df, 'S06', 'D1', 588.0, 0.975, 'truth', truth[:, 0], truth[:, 1])

In [11]:
df

,Subject,Electrode,theta,pdur,type,data,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,S05,C3,36.3,0.075,truth,4.8611,14.65022,43.77047,74.38898,133.87953,224.19096,141.47024,126.46864,99.93162,82.05364,76.4633,67.05204
1,S05,C3,36.3,0.075,pred,4.98067,14.64679,44.2925,74.27555,133.84811,221.21082,141.84635,127.23795,101.08131,87.05417,77.23261,70.90287
2,S06,A1,6.1,0.075,truth,4.70684,14.21718,44.52019,73.20578,139.45736,229.38809,78.94737,73.42105,58.68421,55.78947,53.68421,50.52632
3,S06,A1,6.1,0.075,pred,4.92104,14.20334,44.50573,73.42011,137.21058,222.77886,82.89474,74.21053,58.94737,53.42105,46.84211,44.21053
4,S05,C3,307.5,0.975,truth,5.0,14.81801,43.91469,73.32742,131.74407,214.67673,24.85981,22.61682,22.99065,24.85981,24.01869,19.62617
5,S05,C3,307.5,0.975,pred,5.25019,15.37071,45.0,71.55891,131.74407,214.67673,28.50467,25.88785,20.93458,19.25234,18.69159,18.8785
6,S06,A1,94.5,0.975,truth,5.0,15.0,46.11213,76.99664,140.03539,228.18742,20.51724,16.83908,15.17241,14.65517,13.3908,12.18391
7,S06,A1,94.5,0.975,pred,5.06141,15.0,46.11213,76.99664,140.03539,225.41891,20.51724,18.56322,15.22989,13.96552,13.04598,12.93103
8,S05,B3,21.1,0.075,truth,5.0,15.14525,45.0,74.99495,135.0,224.98486,112.83784,92.56757,70.27027,76.35135,61.48649,61.48649
9,S05,C2,10.5,0.075,truth,4.7549,14.72461,45.31173,76.40481,137.79166,234.09605,214.59597,191.10352,131.81568,105.30261,93.52883,90.46412
10,S06,B1,2500.0,0.075,truth,5.04958,15.11228,45.25887,76.02583,135.40329,225.42409,202.38095,177.38095,159.52381,141.66667,130.95238,120.2381
11,S06,C2,230.0,0.075,truth,5.26202,15.73428,45.90965,76.21561,135.84947,225.12285,269.35835,252.1615,156.76998,159.77433,134.8559,128.48015
12,S05,B3,147.0,0.975,truth,5.0516,15.0,44.54033,74.42302,132.25607,218.73103,29.55563,23.7101,23.90231,22.40522,19.37753,19.01605
13,S05,C2,54.0,0.975,truth,4.94796,15.0,45.95159,76.72857,139.30471,232.60679,24.84375,23.125,22.5,20.9375,20.9375,20.3125
14,S06,B1,2900.0,0.975,truth,5.0,14.84678,44.08536,72.91034,132.25607,218.73103,23.0,25.16667,25.16667,22.5,25.83333,22.83333
15,S06,C2,900.0,0.975,truth,4.77221,14.6227,44.51137,74.30683,135.43058,226.54974,34.34783,34.13043,30.21739,30.43478,26.73913,25.0
16,S05,A1,10.5,0.075,truth,4.83173,14.27496,42.65204,70.9781,125.93917,209.36605,106.56324,91.78543,69.01394,59.45306,56.69734,51.4436
17,S05,C4,49.5,0.075,truth,5.0369,15.18142,45.88949,78.59943,140.05534,233.28153,179.04947,127.50746,105.86506,89.87519,84.23171,78.52492
18,S06,B2,216.0,0.075,truth,4.88165,14.70626,44.32818,73.40122,131.93299,218.34075,251.47059,207.35294,157.35294,132.35294,141.17647,122.05882
19,S06,D1,188.0,0.075,truth,4.81146,14.80072,43.60594,71.79073,128.81898,216.41555,405.88235,281.17647,260.0,222.35294,182.35294,121.17647
20,S05,A1,154.0,0.975,truth,5.02108,15.16171,46.26343,77.70989,139.67851,232.56079,24.3662,21.12676,18.73239,16.90141,15.35211,14.3662
21,S05,C4,141.8,0.975,truth,5.04799,15.0,45.0,75.37929,133.71647,226.13788,18.29657,15.35011,18.08696,17.61648,16.2984,15.51121
22,S06,B2,546.0,0.975,truth,5.0,15.14525,45.87574,77.94229,140.30555,236.09113,30.54545,28.18182,28.54545,28.72727,26.54545,24.18182
23,S06,D1,588.0,0.975,truth,5.04799,15.0,44.57216,75.37929,133.71647,223.98784,30.89286,29.28571,29.64286,30.53571,27.5,23.57143

In [12]:
writer = pd.ExcelWriter(environ['SECOND_SIGHT_DATA'] + '/horsager2009/fixed-duration.xlsx')

In [13]:
df.to_excel(writer,'Sheet1')

In [14]:
writer.save()